### ISSUE TITLE
Compiling on the Pi 3

### ISSUE THREAD

**Issue by studwellm** [brandon-bailey/rtl8822bu#1]
**Installing on the Raspberry Pi 3**
I  ran into an issue compiling this driver for the rPi 3 running Raspbian. I had updated the system and installed newest headers as well however, make** was spitting an **error 2**. I've attached the error, debug, and the error text.

**System build info :** Linux 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

**Solution :** make -j $(nproc) ARCH=arm

This was caught by one of my colleagues and it seems that make was trying to compile for *arm71+* instead of just *arm* which is what seems to work on the Pi.

I hope this helps.

Attached Files:
[Edimax EW-7822ULC Driver Make Debug.txt](https://github.com/brandon-bailey/rtl8822bu/files/968332/Edimax.Driver.Make.Debug.txt)
[Edimax EW-7822ULC Driver Make Error.txt](https://github.com/brandon-bailey/rtl8822bu/files/968331/Edimax.Driver.Make.Error.txt)

**Comment by brandon-bailey** [comment]
Thank you for submitting this issue, I just commited some changes that should take care of this issue. With the new commit you can edit the Makefile and set:
`CONFIG_PLATFORM_ARM_RPI = y` and 
`CONFIG_PLATFORM_I386_PC = n`

If this solves your issue please let me know and I will close this issue.

**Comment by Krakn** [comment]
@brandon-bailey 

3c02cba does fix the issue. Thanks!
