### ISSUE TITLE
Ubuntu 20.04 with kernel 5.4.0-42-generic.

### ISSUE THREAD

**Issue by ktmlleska** [brandon-bailey/rtl8822bu#27]
Hi,

I'm trying to install the drivers for my Asus nano AC-53 on the ubuntu 20.04 but when I try to sudo modprobe 8822bu nothing happens, is like the terminal gets freeze.

Do you know any solution on this?

thanks.

**Comment by brandon-bailey** [comment]
after modprobe have you tried to run lsmod to see if the module is loaded?

**Comment by ktmlleska** [comment]
Thanks Brandon, is all fixed now, I had to reinstall ubuntu, something was wrong with the PCI or USB because when I did lsusb the terminal was hanging, after reinstalling ubuntu everything was working smooth. Thanks.
