### ISSUE TITLE
RF performance is not good 

### ISSUE THREAD

**Issue by ycchangtw** [brandon-bailey/rtl8822bu#3]
Based on the following latest driver plus the patch here
http://www.edimax.com/edimax/mw/cufiles/files/download/Driver_Utility/EW-7822ULC_Linux_Driver_1.0.0.9.zip

I made some comparison, and found there's a huge RF performance between the latest driver and repository. 

1. Same 2x2 AP , latest driver can reach 2x2 MCS3~4 (TX rate)
2. Old driver only reach 1x1 MCS4~5(TX rate)

**Comment by brandon-bailey** [comment]
Thanks for bringing this up, Edimax did not have a driver when I released this. I will be sure to merge their code.
